stages:
  - install
  - build

variables:
  NODE_ENV: "production"
  VITE_VERSION: "5.4.10"  # Указываем версию Vite

cache:
  paths:
    - node_modules/
    - .yarn/cache

before_script:
  - 'echo "Using Node.js version $(node -v)"'
  - 'echo "Using Vite version $VITE_VERSION"'

install_dependencies:
  stage: install
  image: node:18  # Замените на нужную версию Node.js
  script:
    - yarn install
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
      - .yarn/cache

build:
  stage: build
  image: node:18  # Замените на нужную версию Node.js
  script:
    - yarn run build
  artifacts:
    paths:
      - dist/
  only:
    - main  # Указываем ветку, для которой запускается сборка
